@startuml

start

while (stuff available?)
  if (used it in the last year?) then (yes)
    if (used it more than twice?) then (yes)
        :düsseldorf;
      else (no)
        :djakarta;
      endif
  else (no)
    :dustbin;
  endif
endwhile

stop

@enduml
